version: "3"
services:
    app:
        build:
            context: .
            args:
                - APP_NAME=${APP_NAME}
                - ICON_NAME=${ICON_NAME}
                - FOLDER_NAME=${FOLDER_NAME}
